AllCops:
  RunRailsCops: true

  Exclude:
    - db/schema.rb

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/AndOr:
  Enabled: false
